<?php

/**
 * @file
 * Contains commerce_coupon_conditions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_coupon_conditions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lfi_commerce module.
    case 'help.page.lfi_commerce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Commerce integration LFI') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function commerce_coupon_conditions_entity_type_alter(array $entity_types) {
  $entity_types['commerce_promotion_coupon']->setClass('Drupal\commerce_coupon_conditions\Entity\Coupon');
}
